### ISSUE TITLE
FE 상태관리 라이브러리 사용

### ISSUE THREAD

**Issue by hwanfront** [tooktak/advanced-bookmark#39]
props 넘겨주려다 보니 복잡해져서 상태관리 라이브러리를 사용하겠습니다.
mobx 나 redux 는 프로젝트 크기에 비해 너무 과하고 무거워 질 느낌이라서 recoil 을 사용해보겠습니다. 
지난번에 사용해보니 간편하고 좋더라구요.

**Comment by hwanfront** [comment]
일단은 context api 로 해결해보겠슴다

**Comment by junhodo** [comment]
online comment
mobx > recoil? -> recoil이 더 작다
