### ISSUE TITLE
webpack 으로 번들링(build) 할 때 eslint 실행

### ISSUE THREAD

**Issue by hwanfront** [tooktak/advanced-bookmark#43]
webpack 으로 번들링(npm run build 또는 npm run watch) 할 때 eslint 실행할 수 있는데 설정할까요?
- 지원하는 타입스크립트 버전이 약간 벗어난다는 문제가 있긴 한데
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.6.2

Please only submit bug reports when using the officially supported version.

=============
```
- 플러그인을 추가하고 build 하면 이렇게 뜸
![image](https://user-images.githubusercontent.com/65995108/156913017-64d50f5c-d216-4011-b280-d88e91a21905.png)

**Comment by junhodo** [comment]
해당 플러그인을 추가하면 빌드할 떄 lint를 같이 돌려주는건가요?

**Comment by hwanfront** [comment]
> 해당 플러그인을 추가하면 빌드할 떄 lint를 같이 돌려주는건가요?

넵 같이 돌려줍니다

**Comment by junhodo** [comment]
저는 좋은 것 같네용!~
