### ISSUE TITLE
chrome.bookmark api에서 favIconUrl 속성 

### ISSUE THREAD

**Issue by hwanfront** [tooktak/advanced-bookmark#51]
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/qr6FKXD9sdY
https://stackoverflow.com/questions/68567887/display-a-favicon-in-a-chrome-extension-newtab-page-using-manifest-v3
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/eteUTrlGCek

bookmark api 에서 favicon url 이 없음
- favicon (왼쪽 크롬 아이콘)
![image](https://user-images.githubusercontent.com/65995108/158066168-0402d1f7-6856-4155-99f5-ce2a3f196cd7.png)

manifest v2 에서는 `chrome://favicon/ ... ` 으로 가능한데 v3에선 안됌
https://bugs.chromium.org/p/chromium/issues/detail?id=104102#c36
1분기에 다룬다고는 하는데 언제될지 모르겠음

**Comment by junhodo** [comment]
> chrome store에 upload 하려면 v3를 사용해야한다

**Comment by hwanfront** [comment]
`http://www.google.com/s2/favicons?domain_url={url}`
일단 chrome extension 자체에서 제공하는 방법은 아닌데 해당 url을 통해서 favicon을 불러올 수 있네요.
